// Auto-generated by scripts/create-stripe-products.js
// DO NOT EDIT MANUALLY - regenerate with: node scripts/create-stripe-products.js

export interface StripeProductConfig {
  name: string;
  productId: string;
  priceId: string;
  price: number;
  currency: string;
  interval: string;
}

export const STRIPE_PRODUCTS: StripeProductConfig[] = [
  {
    name: "Starter",
    productId: "prod_UAnf1jBUGaufmP",
    priceId: "price_1TCS4MKPmxRibChZlo5IvcoY",
    price: 9,
    currency: "USD",
    interval: "month",
  },
  {
    name: "Solo",
    productId: "prod_UAnfHnRmvoyaSp",
    priceId: "price_1TCS4OKPmxRibChZBoLYSEFO",
    price: 29,
    currency: "USD",
    interval: "month",
  },
  {
    name: "Team",
    productId: "prod_UAnfqLJnuZv6FE",
    priceId: "price_1TCS4PKPmxRibChZOIscjX6W",
    price: 79,
    currency: "USD",
    interval: "month",
  },
  {
    name: "Enterprise Cloud",
    productId: "prod_UAnf8gkAg7peli",
    priceId: "price_1TCS4RKPmxRibChZlVxc107m",
    price: 299,
    currency: "USD",
    interval: "month",
  },
  {
    name: "Enterprise Self-Hosted",
    productId: "prod_UAnfhexWDcTOWR",
    priceId: "price_1TCS4SKPmxRibChZNKvEDgCE",
    price: 499,
    currency: "USD",
    interval: "month",
  },
];

// Convenience lookups
export const STRIPE_PRODUCTS_BY_NAME = Object.fromEntries(
  STRIPE_PRODUCTS.map((p) => [p.name, p]),
) as Record<string, StripeProductConfig>;

export const STRIPE_PRICES_BY_PRODUCT_ID = Object.fromEntries(
  STRIPE_PRODUCTS.map((p) => [p.productId, p.priceId]),
) as Record<string, string>;
